server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/taoxq?serverTimezone=Asia/Shanghai
    password: 123123
  jpa:
    open-in-view: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/taoxq_info
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8
        max-idle: 10
        max-wait: 1ms
        min-idle: 5
      shutdown-timeout: 100ms
    port: 6379
